<a href="https://colab.research.google.com/github/Adityajeegari/23CSBTB39-40/blob/main/Assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

print("List 1:", list1)
print("List 2:", list2)

array1 = np.array(list1)
array2 = np.array(list2)

print("Array 1:", array1)
print("Array 2:", array2)

print("Type of list1:", type(list1))
print("Type of array1:", type(array1))

multiplication = array1 * array2
print("Multiplication of arrays:", multiplication)

division = array1 / array2
print("Division of arrays:", division)

power = np.power(array1, 2)
print("Power of array1:", power)

addition = array1 + array2
print("Addition of arrays:",addition)

sin_values = np.sin(array1)
print(sin_values)

log_values = np.log(array1)
print(log_values)

log2_values = np.log2(array1)
print(log2_values)

exp_values = np.exp(array1)
print(exp_values)


List 1: [1, 2, 3, 4, 5]
List 2: [6, 7, 8, 9, 10]
Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
Type of list1: <class 'list'>
Type of array1: <class 'numpy.ndarray'>
Multiplication of arrays: [ 6 14 24 36 50]
Division of arrays: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Power of array1: [ 1  4  9 16 25]
Addition of arrays: [ 7  9 11 13 15]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
